development:
  host: '127.0.0.1'
  port: 9042
  keyspace: piersky_development
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: piersky_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  host: '127.0.0.1'
  port: 9042
  keyspace: piersky_production
  max_retries: 3
  retry_delay: 0.5
  newrelic: false
  # hosts:
  #   - 'cass1.piersky.biz'
  #   - 'cass2.piersky.biz'
  #   - 'cass3.piersky.biz'
  # port: 9042
  # keyspace: piersky_production
  # username: 'myappuser'
  # password: 'password1'
  # max_retries: 3
  # retry_delay: 0.5
  # newrelic: true
  # replication:
  #   class: SimpleStrategy
  #   replication_factor: 1
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
