default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: piersky_development
  username: mysql
  password: 'root'
  host: localhost

test:
  <<: *default
  database: piersky_test
  username: mysql
  password: 'root'
  host: localhost

production:
  <<: *default
  adapter: mysql2
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>